/* Печатает фактическую раскладку структур libfuse3 и ядра.
 *
 * Зачем: адаптер обязан положить указатели на свои функции в
 * struct fuse_operations по правильным смещениям. Ошибка в порядке не даёт
 * ошибки компиляции — она даёт вызов не той функции. Документация и память
 * тут не эталон; эталон — компилятор на целевой платформе.
 *
 * Вывод сохраняется фикстурой, тест сверяет с ним константы C#. Тот же приём,
 * что в M1 с git: эталоном служит сам формат, а не наше представление о нём.
 *
 *   gcc -o probe tools/fuse-abi-probe.c $(pkg-config --cflags --libs fuse3)
 *   ./probe > tests/Gitfs.Mount.Fuse.Tests/fixtures/fuse-abi.txt
 */
#define FUSE_USE_VERSION 31
#include <fuse3/fuse.h>
#include <stdio.h>
#include <stddef.h>
#include <sys/stat.h>
#include <sys/statvfs.h>

#define SIZE(t)      printf("sizeof %-28s %zu\n", #t, sizeof(t))
#define OFF(t, f)    printf("offset %-28s %zu\n", #t "." #f, offsetof(t, f))

int main(void)
{
    printf("# generated by tools/fuse-abi-probe.c — do not edit by hand\n");
    printf("arch %s\n", sizeof(void *) == 8 ? "64" : "32");
    printf("fuse_version %d\n", fuse_version());

    SIZE(struct fuse_operations);
    OFF(struct fuse_operations, getattr);
    OFF(struct fuse_operations, readlink);
    OFF(struct fuse_operations, mknod);
    OFF(struct fuse_operations, mkdir);
    OFF(struct fuse_operations, unlink);
    OFF(struct fuse_operations, rmdir);
    OFF(struct fuse_operations, symlink);
    OFF(struct fuse_operations, rename);
    OFF(struct fuse_operations, link);
    OFF(struct fuse_operations, chmod);
    OFF(struct fuse_operations, chown);
    OFF(struct fuse_operations, truncate);
    OFF(struct fuse_operations, open);
    OFF(struct fuse_operations, read);
    OFF(struct fuse_operations, write);
    OFF(struct fuse_operations, statfs);
    OFF(struct fuse_operations, flush);
    OFF(struct fuse_operations, release);
    OFF(struct fuse_operations, fsync);
    OFF(struct fuse_operations, opendir);
    OFF(struct fuse_operations, readdir);
    OFF(struct fuse_operations, releasedir);
    OFF(struct fuse_operations, init);
    OFF(struct fuse_operations, destroy);
    OFF(struct fuse_operations, access);
    OFF(struct fuse_operations, create);
    OFF(struct fuse_operations, utimens);

    SIZE(struct stat);
    OFF(struct stat, st_ino);
    OFF(struct stat, st_mode);
    OFF(struct stat, st_nlink);
    OFF(struct stat, st_uid);
    OFF(struct stat, st_gid);
    OFF(struct stat, st_size);
    OFF(struct stat, st_blksize);
    OFF(struct stat, st_blocks);
    OFF(struct stat, st_atim);
    OFF(struct stat, st_mtim);
    OFF(struct stat, st_ctim);

    SIZE(struct fuse_file_info);
    OFF(struct fuse_file_info, flags);
    OFF(struct fuse_file_info, fh);

    SIZE(struct statvfs);
    OFF(struct statvfs, f_bsize);
    OFF(struct statvfs, f_frsize);
    OFF(struct statvfs, f_blocks);
    OFF(struct statvfs, f_bfree);
    OFF(struct statvfs, f_bavail);
    OFF(struct statvfs, f_files);
    OFF(struct statvfs, f_ffree);
    OFF(struct statvfs, f_namemax);

    SIZE(struct fuse_args);
    OFF(struct fuse_args, argc);
    OFF(struct fuse_args, argv);
    OFF(struct fuse_args, allocated);

    /* через него колбэк находит свой экземпляр адаптера: в процессе может
       быть смонтировано несколько томов, статическое поле не подойдёт.
       Печатаем ТОЛЬКО то, чем адаптер пользуется: тест требует, чтобы
       каждая строка отсюда с чем-то сверялась, иначе проба создаёт
       видимость покрытия вместо покрытия */
    SIZE(struct fuse_context);
    OFF(struct fuse_context, private_data);

    SIZE(struct timespec);
    OFF(struct timespec, tv_sec);
    OFF(struct timespec, tv_nsec);
    return 0;
}
